"""adding farmer rship

Revision ID: 60e339bb0d53
Revises: c7bc0afacc83
Create Date: 2023-12-07 10:55:00.393086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60e339bb0d53'
down_revision: Union[str, None] = 'c7bc0afacc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.alter_column('products', 'farmer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('products_farmer_email_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'farmer_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('farmer_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('products_farmer_email_fkey', 'products', 'farmers', ['farmer_email'], ['email'])
    op.alter_column('products', 'farmer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('customers',
    sa.Column('id', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    # ### end Alembic commands ###
