"""rectoring

Revision ID: b4f4dff382b4
Revises: 61527b2a00fc
Create Date: 2023-12-02 06:40:05.164024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4f4dff382b4'
down_revision: Union[str, None] = '61527b2a00fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'phone')
    op.drop_column('farmers', 'created_at')
    op.drop_column('farmers', 'name')
    op.drop_column('farmers', 'password')
    op.drop_column('farmers', 'location')
    op.drop_column('farmers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('email', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('farmers', sa.Column('location', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('farmers', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('farmers', sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('farmers', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('farmers', sa.Column('phone', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
