"""adding relationship

Revision ID: 928cb77e39fe
Revises: 7d3f13ac1cde
Create Date: 2023-11-25 14:23:53.547739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928cb77e39fe'
down_revision: Union[str, None] = '7d3f13ac1cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('farmer_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'products', 'farmers', ['farmer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'farmer_id')
    # ### end Alembic commands ###
