"""refactored models

Revision ID: b4533ea5245b
Revises: 9df6f23f65b7
Create Date: 2023-11-24 16:11:05.995709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4533ea5245b'
down_revision: Union[str, None] = '9df6f23f65b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=60), nullable=False))
    op.alter_column('farmers', 'bio',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farmers', 'bio',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
