"""adding image

Revision ID: f610735966ac
Revises: 5273967787bb
Create Date: 2023-11-28 03:32:09.127667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f610735966ac'
down_revision: Union[str, None] = '5273967787bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
